import type { EmbeddingProvider, LlmProvider } from "@/lib/env";

/** Non-secret application defaults. Change deployment-specific values here. */
export const appConfig = {
  app: {
    url: "https://obsi-relay.vrj02.dev/",
    name: "Obsi-Relay",
  },
  supabase: {
    url: "https://szctlzflfbcmlrztituq.supabase.co",
    storageBucket: "vaults",
  },
  auth: {
    sessionDays: 7,
    devBypass: true,
  },
  llm: {
    provider: "mistral" as LlmProvider,
    model: "ministral-14b-latest",
    temperature: 0.2,
    maxOutputTokens: 2000,
    requestTimeoutMs: 60_000,
    openaiBaseUrl: "",
    azureResourceName: "",
    azureApiVersion: "2024-10-21",
    ollamaBaseUrl: "http://localhost:11434/v1",
    openaiCompatibleName: "custom",
    openaiCompatibleBaseUrl: "",
  },
  embedding: {
    provider: "mistral" as EmbeddingProvider,
    model: "mistral-embed",
    dimensions: 1024,
    batchSize: 64,
    concurrency: 3,
    docPrefix: "",
    queryPrefix: "",
  },
  chunking: {
    strategy: "markdown" as "markdown" | "recursive",
    sizeTokens: 512,
    overlapTokens: 64,
    minTokens: 48,
    maxTokens: 1024,
    prependHeadings: true,
    keepCodeBlocks: true,
  },
  retrieval: {
    hybrid: true,
    rrfK: 60,
    candidateK: 40,
    topK: 8,
    minScore: 0.2,
    neighborWindow: 1,
    queryExpansion: true,
    queryVariants: 3,
    reranker: "none" as "none" | "cohere" | "jina",
    rerankerModel: "rerank-v3.5",
    contextTokenBudget: 6000,
    hnswM: 16,
    hnswEfConstruction: 64,
    hnswEfSearch: 100,
  },
  ingestion: {
    maxVaultUploadMb: 200,
    concurrency: 6,
    excludeGlobs: [
      ".obsidian/**",
      ".trash/**",
      ".git/**",
      "**/node_modules/**",
      "**/*.excalidraw.md",
    ],
    respectPrivacyFrontmatter: true,
    privateTags: ["private", "secret", "noindex"],
  },
  email: {
    fromEmail: "relay@obsi-relay.vrj02.dev",
    fromName: "Obsi-Relay",
    replyTo: "ask@obsi-relay.vrj02.dev",
    inboundDomain: "ask.obsi-relay.vrj02.dev",
    dryRun: true,
    allowedSenderDomains: [] as string[],
    rateLimitPerSenderPerDay: 10,
  },
  grounding: {
    enabled: true,
    provider: "",
    model: "",
    autosendThreshold: 0.8,
    reviewThreshold: 0.5,
    requireCitations: true,
    failMode: "review" as "review" | "block" | "send",
  },
  evaluator: {
    judgeProvider: "",
    judgeModel: "",
    dataset: "src/evaluator/datasets/golden.jsonl",
    outputDir: "eval-results",
    concurrency: 4,
    repeats: 1,
    passThreshold: 0.7,
  },
  logLevel: "info" as "debug" | "info" | "warn" | "error",
} as const;